name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up event name
        run: echo "The event that triggered the workflow is ${{ github.event_name }}"
      - name: Set up branch name
        run: echo "The branch name is ${{ github.ref_name }}"
      - name: List all files
        run: |
          echo "List of all files in the repository:"
          git ls-files
      
