name: GitHub Actions Demo

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up event name
        run: echo "The event that triggered the workflow is ${{ github.event_name }}"
      - name: Set up branch name
        run: echo "The branch name is ${{ github.ref_name }}"
      - name: List all files
        run: |
          echo "List of all files in the repository:"
          git ls-files      
  Test:
    needs: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Testing
        run: echo "Testing..."

  Load-Test:
    needs: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: Load Testing
        run: |
          echo "Testing..."
          sleep 15

  Production:
    needs: [Test, Load-Test]
    runs-on: ubuntu-latest
    if: github.event.inputs.deploy == 'production'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - name: Deploying Step 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Deploying Step 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Deploying Step 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Deploying Step 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Deploying Step 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
